name: Build
on:
  push:
    branches:
      - main

jobs:
  # First, run all the tests
  Run-Go-Tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run tests
        run: go test -v ./api/...
      - name: Build the binary
        run: go build ./api/cmd/server -o api 
      - name: Upload to GH
        uses: actions/upload-artifact@v4
        with:
          path: ./api